### ISSUE TITLE
Linux Build Error

### ISSUE THREAD

**Issue by kira-96** [Chenyating/vuepress-theme-ting#1]
[tingFeel.vue](https://github.com/Chenyating/vuepress-theme-ting/blob/master/docs/.vuepress/theme/components/tingFeel.vue)
`import $ from 'jQuery';`
不确定是不是这里导致的，编译的时候一直提示找不到'jQuery'，改成'jquery'之后就可以了。
Windows上编译正常。

**Comment by Chenyating** [comment]
你的做法是正确的，我写错了。
